### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ong-yinggao98** [AY2021S1-CS2103T-W15-2/tp#206]
Different formats:
~~1. Schedule commands use full words as their prefixes~~
2. Some Note commands do not need prefixes

Coverage:
It's been dropping consistently with every PR, it's fallen from 79% to 75% and the next few PRs will continue to decrease it by 1-2%

We need to freeze all new code soon and get our code coverage up to par, especially since these are all features untested in the previous run. We will also need to start going full time into the DG as well.

**Comment by AlexCQY** [comment]
resolved schedule part

> Different formats:
> 
> 1. Schedule commands use full words as their prefixes
> 2. Some Note commands do not need prefixes
> 
> Coverage:
> It's been dropping consistently with every PR, it's fallen from 79% to 75% and the next few PRs will continue to decrease it by 1-2%
> 
> We need to freeze all new code soon and get our code coverage up to par, especially since these are all features untested in the previous run. We will also need to start going full time into the DG as well.
