### ISSUE TITLE
End Time Start Time error message can be clearer

### ISSUE THREAD

**Issue by hogantan** [AY2021S1-CS2103T-W15-2/tp#235]
Class Time error message for end and start time can be clearer

![image](https://user-images.githubusercontent.com/65152263/98458709-7c75b300-21ce-11eb-8edf-83573c8b14cd.png)

**Comment by ong-yinggao98** [comment]
Classtime format message could be standardised with the error messages in command syntax
(i.e DAY_OF_WEEK START_TIME-END_TIME)

**sample description**
Class time should be in the following format: `DAY_OF_WEEK` `START_TIME`-`END_TIME`
`DAY_OF_WEEK`: 1-7 representing Mon-Sun
`START_TIME`/`END_TIME`: Lesson time in 24hr clock
e.g 1 1200-1300
