### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by hogantan** [AY2021S1-CS2103T-W15-2/tp#242]
Full screen issue

Notes list expanding issue

**Comment by ong-yinggao98** [comment]
![NVIDIA_Share_2020-11-08_14-35-44](https://user-images.githubusercontent.com/52755148/98458968-eee79280-21d0-11eb-94c5-79af65d6e5f0.jpg)

NoteBook expands with more notes added, but it could be flush with the command result from the start
