### ISSUE TITLE
ClassTime should check if startTime is earlier than endTime

### ISSUE THREAD

**Issue by ong-yinggao98** [AY2021S1-CS2103T-W15-2/tp#59]
Right now it only checks if the start and end time lie within the 24h clock, perhaps we could do an extra step of validation?

e.g. in the constructor if `startTime.compareTo(endTime) > 0` you could throw an `IllegalArgumentException` with another `MESSAGE_CONSTRAINT` that says the start time can't be after the end time.

**Comment by VaishakAnand** [comment]
Good point, I'll do so in my next PR, thanks!
