### ISSUE TITLE
Rework Year class

### ISSUE THREAD

**Issue by ong-yinggao98** [AY2021S1-CS2103T-W15-2/tp#61]
Right now `Year` is just a string that takes in any alphanumeric sequence, so if someone wants to he can just create students of years "sec 4", "Secondary 4", etc. 
Perhaps we could turn it into a container class that contains a school level and the year instead.
e.g. `Year(Level.SECONDARY, 4)` would create a Year object of level Secondary School and year 4.
This might help to produce a standard format for the students' `year` data.

**Comment by AlexCQY** [comment]
Good point. This would make searching and filtering the `year` data easier. Based on this, I guess we may have to exhaust all possible levels of student that a tutor may have? My concern is that IP, IB, MOE mainstream tracks have different naming in their levels. Furthermore, there could be other level naming, for eg a tutor teaching music or arts may have different levels naming for their students.

**Comment by ong-yinggao98** [comment]
> My concern is that IP, IB, MOE mainstream tracks have different naming in their levels. Furthermore, there could be other level naming, for eg a tutor teaching music or arts may have different levels naming for their students.

I think this is not too bad a problem since our primary target was pri/sec/jc tutors so if we frame our target audience that way we still can meet their requirements

**Comment by AlexCQY** [comment]
Oh ya our target was pri/sec/jc nice.
